# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import catalog_pb2 as catalog__pb2


class CatalogStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/Catalog/Query',
                request_serializer=catalog__pb2.QueryRequest.SerializeToString,
                response_deserializer=catalog__pb2.QueryReply.FromString,
                )
        self.Update = channel.unary_unary(
                '/Catalog/Update',
                request_serializer=catalog__pb2.UpdateRequest.SerializeToString,
                response_deserializer=catalog__pb2.UpdateReply.FromString,
                )
        self.LeaderNotification = channel.unary_unary(
                '/Catalog/LeaderNotification',
                request_serializer=catalog__pb2.LeaderNotificationRequest.SerializeToString,
                response_deserializer=catalog__pb2.LeaderNotificationReply.FromString,
                )


class CatalogServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaderNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=catalog__pb2.QueryRequest.FromString,
                    response_serializer=catalog__pb2.QueryReply.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=catalog__pb2.UpdateRequest.FromString,
                    response_serializer=catalog__pb2.UpdateReply.SerializeToString,
            ),
            'LeaderNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaderNotification,
                    request_deserializer=catalog__pb2.LeaderNotificationRequest.FromString,
                    response_serializer=catalog__pb2.LeaderNotificationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Catalog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Catalog(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Catalog/Query',
            catalog__pb2.QueryRequest.SerializeToString,
            catalog__pb2.QueryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Catalog/Update',
            catalog__pb2.UpdateRequest.SerializeToString,
            catalog__pb2.UpdateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LeaderNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Catalog/LeaderNotification',
            catalog__pb2.LeaderNotificationRequest.SerializeToString,
            catalog__pb2.LeaderNotificationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
