# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\"I\n\x10\x61\x64\x64ToConfRequest\x12\x0f\n\x07keyName\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x15\n\rorder_host_id\x18\x03 \x01(\t\"D\n\x0e\x61\x64\x64ToConfReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x10\n\x08leaderid\x18\x02 \x01(\t\x12\x10\n\x08leaderip\x18\x03 \x01(\t\"\'\n\x16removeOrderHostRequest\x12\r\n\x05value\x18\x01 \x01(\t\"&\n\x14removeOrderHostReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\".\n\x15getConfigDetailsReply\x12\x15\n\rconfigdetails\x18\x01 \x01(\t\"!\n\x10getConfigRequest\x12\r\n\x05\x64ummy\x18\x01 \x01(\t2\xc1\x01\n\x06\x43onfig\x12\x31\n\tAddToConf\x12\x11.addToConfRequest\x1a\x0f.addToConfReply\"\x00\x12\x43\n\x0fRemoveOrderHost\x12\x17.removeOrderHostRequest\x1a\x15.removeOrderHostReply\"\x00\x12?\n\x10GetConfigDetails\x12\x11.getConfigRequest\x1a\x16.getConfigDetailsReply\"\x00\x62\x06proto3')



_ADDTOCONFREQUEST = DESCRIPTOR.message_types_by_name['addToConfRequest']
_ADDTOCONFREPLY = DESCRIPTOR.message_types_by_name['addToConfReply']
_REMOVEORDERHOSTREQUEST = DESCRIPTOR.message_types_by_name['removeOrderHostRequest']
_REMOVEORDERHOSTREPLY = DESCRIPTOR.message_types_by_name['removeOrderHostReply']
_GETCONFIGDETAILSREPLY = DESCRIPTOR.message_types_by_name['getConfigDetailsReply']
_GETCONFIGREQUEST = DESCRIPTOR.message_types_by_name['getConfigRequest']
addToConfRequest = _reflection.GeneratedProtocolMessageType('addToConfRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDTOCONFREQUEST,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:addToConfRequest)
  })
_sym_db.RegisterMessage(addToConfRequest)

addToConfReply = _reflection.GeneratedProtocolMessageType('addToConfReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDTOCONFREPLY,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:addToConfReply)
  })
_sym_db.RegisterMessage(addToConfReply)

removeOrderHostRequest = _reflection.GeneratedProtocolMessageType('removeOrderHostRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEORDERHOSTREQUEST,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:removeOrderHostRequest)
  })
_sym_db.RegisterMessage(removeOrderHostRequest)

removeOrderHostReply = _reflection.GeneratedProtocolMessageType('removeOrderHostReply', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEORDERHOSTREPLY,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:removeOrderHostReply)
  })
_sym_db.RegisterMessage(removeOrderHostReply)

getConfigDetailsReply = _reflection.GeneratedProtocolMessageType('getConfigDetailsReply', (_message.Message,), {
  'DESCRIPTOR' : _GETCONFIGDETAILSREPLY,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:getConfigDetailsReply)
  })
_sym_db.RegisterMessage(getConfigDetailsReply)

getConfigRequest = _reflection.GeneratedProtocolMessageType('getConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCONFIGREQUEST,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:getConfigRequest)
  })
_sym_db.RegisterMessage(getConfigRequest)

_CONFIG = DESCRIPTOR.services_by_name['Config']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDTOCONFREQUEST._serialized_start=16
  _ADDTOCONFREQUEST._serialized_end=89
  _ADDTOCONFREPLY._serialized_start=91
  _ADDTOCONFREPLY._serialized_end=159
  _REMOVEORDERHOSTREQUEST._serialized_start=161
  _REMOVEORDERHOSTREQUEST._serialized_end=200
  _REMOVEORDERHOSTREPLY._serialized_start=202
  _REMOVEORDERHOSTREPLY._serialized_end=240
  _GETCONFIGDETAILSREPLY._serialized_start=242
  _GETCONFIGDETAILSREPLY._serialized_end=288
  _GETCONFIGREQUEST._serialized_start=290
  _GETCONFIGREQUEST._serialized_end=323
  _CONFIG._serialized_start=326
  _CONFIG._serialized_end=519
# @@protoc_insertion_point(module_scope)
