# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frontend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66rontend.proto\"$\n\x11InvalidateRequest\x12\x0f\n\x07toylist\x18\x01 \x01(\t\"!\n\x0fInvalidateReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\x42\n\x05\x43\x61\x63he\x12\x39\n\x0fInvalidateCache\x12\x12.InvalidateRequest\x1a\x10.InvalidateReply\"\x00\x62\x06proto3')



_INVALIDATEREQUEST = DESCRIPTOR.message_types_by_name['InvalidateRequest']
_INVALIDATEREPLY = DESCRIPTOR.message_types_by_name['InvalidateReply']
InvalidateRequest = _reflection.GeneratedProtocolMessageType('InvalidateRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVALIDATEREQUEST,
  '__module__' : 'frontend_pb2'
  # @@protoc_insertion_point(class_scope:InvalidateRequest)
  })
_sym_db.RegisterMessage(InvalidateRequest)

InvalidateReply = _reflection.GeneratedProtocolMessageType('InvalidateReply', (_message.Message,), {
  'DESCRIPTOR' : _INVALIDATEREPLY,
  '__module__' : 'frontend_pb2'
  # @@protoc_insertion_point(class_scope:InvalidateReply)
  })
_sym_db.RegisterMessage(InvalidateReply)

_CACHE = DESCRIPTOR.services_by_name['Cache']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INVALIDATEREQUEST._serialized_start=18
  _INVALIDATEREQUEST._serialized_end=54
  _INVALIDATEREPLY._serialized_start=56
  _INVALIDATEREPLY._serialized_end=89
  _CACHE._serialized_start=91
  _CACHE._serialized_end=157
# @@protoc_insertion_point(module_scope)
