# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import frontend_pb2 as frontend__pb2


class CacheStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InvalidateCache = channel.unary_unary(
                '/Cache/InvalidateCache',
                request_serializer=frontend__pb2.InvalidateRequest.SerializeToString,
                response_deserializer=frontend__pb2.InvalidateReply.FromString,
                )


class CacheServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InvalidateCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InvalidateCache': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateCache,
                    request_deserializer=frontend__pb2.InvalidateRequest.FromString,
                    response_serializer=frontend__pb2.InvalidateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Cache', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Cache(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InvalidateCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cache/InvalidateCache',
            frontend__pb2.InvalidateRequest.SerializeToString,
            frontend__pb2.InvalidateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
